
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class BuyTicketFram extends javax.swing.JFrame {

    /**
     * Creates new form TuitionfeeFram
     */
    public BuyTicketFram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentidPanel = new javax.swing.JPanel();
        tutionfeeLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        toTF = new javax.swing.JTextField();
        studentidLabel = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        bkashComboBox = new javax.swing.JComboBox<>();
        selectpaymentmethodLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentidPanel.setBackground(new java.awt.Color(255, 153, 153));

        tutionfeeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tutionfeeLabel.setForeground(new java.awt.Color(255, 255, 255));
        tutionfeeLabel.setText("Buy Ticket");

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        toTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTFActionPerformed(evt);
            }
        });

        studentidLabel.setText("Amount");

        amountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTFActionPerformed(evt);
            }
        });

        nameLabel.setText("Direction");

        bkashComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bikash", "Nogad", "DBBL" }));

        selectpaymentmethodLabel.setText("Select Payment Method");

        sendButton.setBackground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentidPanelLayout = new javax.swing.GroupLayout(studentidPanel);
        studentidPanel.setLayout(studentidPanelLayout);
        studentidPanelLayout.setHorizontalGroup(
            studentidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentidPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(studentidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bkashComboBox, 0, 170, Short.MAX_VALUE)
                    .addComponent(amountTF)
                    .addComponent(toTF)
                    .addComponent(selectpaymentmethodLabel)
                    .addComponent(studentidLabel)
                    .addComponent(nameLabel)
                    .addComponent(backButton)
                    .addComponent(tutionfeeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        studentidPanelLayout.setVerticalGroup(
            studentidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentidPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tutionfeeLabel)
                .addGap(28, 28, 28)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(selectpaymentmethodLabel)
                .addGap(7, 7, 7)
                .addGroup(studentidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bkashComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentidLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentidPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentidPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTFActionPerformed

    private void amountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTFActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        
         String method="",to="",amount="";
     
          
          try {
            method=bkashComboBox.getItemAt(bkashComboBox.getSelectedIndex());
            
             if(method.isEmpty()){
               
                JOptionPane.showMessageDialog(this, "Select Your Method");
            }
        } catch (Exception e) {
        }
        
        
        try {
            to=toTF.getText();
            
            if(to.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Your Wher you want go");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something woring with your go direction name");
        }
        
         try {
            amount=amountTF.getText();
            
            if(amount.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Your Amount");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something woring with your amount");
        }
        
        
        
        if(!(to.isEmpty() || amount.isEmpty() )){
            BuyTicketClass tuitionFeeClass=new BuyTicketClass();
            tuitionFeeClass.setValue(method, to, amount);
            tuitionFeeClass.dataWriteinFile();
            JOptionPane.showMessageDialog(this, "Congress");
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        HomeFram homeFram=new HomeFram();
        homeFram.setVisible(true);
        dispose();

    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTicketFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTicketFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTicketFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTicketFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyTicketFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTF;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> bkashComboBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel selectpaymentmethodLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel studentidLabel;
    private javax.swing.JPanel studentidPanel;
    private javax.swing.JTextField toTF;
    private javax.swing.JLabel tutionfeeLabel;
    // End of variables declaration//GEN-END:variables
}
