
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class HomeFram extends javax.swing.JFrame {

    /**
     * Creates new form HomeFram
     */
    public HomeFram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ticketinfoBtn = new javax.swing.JButton();
        cancleticketBtn = new javax.swing.JButton();
        passangerinfoBtn = new javax.swing.JButton();
        driverinfoBtn = new javax.swing.JButton();
        myprofilelbtn = new javax.swing.JButton();
        supervisorinfoBtn = new javax.swing.JButton();
        notificationBtn = new javax.swing.JButton();
        buyticketBtn = new javax.swing.JButton();
        paidmonyBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        ticketinfoBtn.setBackground(new java.awt.Color(255, 255, 255));
        ticketinfoBtn.setText("Ticket Info");
        ticketinfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketinfoBtnActionPerformed(evt);
            }
        });

        cancleticketBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancleticketBtn.setText("Cancel Ticket");
        cancleticketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleticketBtnActionPerformed(evt);
            }
        });

        passangerinfoBtn.setBackground(new java.awt.Color(255, 255, 255));
        passangerinfoBtn.setText("Passenger Info");
        passangerinfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passangerinfoBtnActionPerformed(evt);
            }
        });

        driverinfoBtn.setBackground(new java.awt.Color(255, 255, 255));
        driverinfoBtn.setText("Driver's Info");
        driverinfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverinfoBtnActionPerformed(evt);
            }
        });

        myprofilelbtn.setBackground(new java.awt.Color(255, 255, 255));
        myprofilelbtn.setText("My Profile");
        myprofilelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myprofilelbtnActionPerformed(evt);
            }
        });

        supervisorinfoBtn.setBackground(new java.awt.Color(255, 255, 255));
        supervisorinfoBtn.setText("Supervisor's Info");
        supervisorinfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorinfoBtnActionPerformed(evt);
            }
        });

        notificationBtn.setBackground(new java.awt.Color(255, 255, 255));
        notificationBtn.setText("Notification");
        notificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBtnActionPerformed(evt);
            }
        });

        buyticketBtn.setBackground(new java.awt.Color(255, 255, 255));
        buyticketBtn.setText("Buy Ticket");
        buyticketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyticketBtnActionPerformed(evt);
            }
        });

        paidmonyBtn.setBackground(new java.awt.Color(255, 255, 255));
        paidmonyBtn.setText("Passenger List");
        paidmonyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidmonyBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcom To Dashbord");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(driverinfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myprofilelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticketinfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(paidmonyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancleticketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(passangerinfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supervisorinfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyticketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel6)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketinfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancleticketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyticketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myprofilelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidmonyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driverinfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supervisorinfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passangerinfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyticketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyticketBtnActionPerformed
        // TODO add your handling code here:
        BuyTicketFram fram=new BuyTicketFram();
        fram.setVisible(true);
        dispose();
    }//GEN-LAST:event_buyticketBtnActionPerformed

    private void supervisorinfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorinfoBtnActionPerformed
        // TODO add your handling code here:
        SupervisorFram fram=new SupervisorFram();
        fram.setVisible(true);
        dispose();
    }//GEN-LAST:event_supervisorinfoBtnActionPerformed

    private void ticketinfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketinfoBtnActionPerformed
        // TODO add your handling code here:
        TicketInfoFram fram=new TicketInfoFram();
        fram.setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketinfoBtnActionPerformed

    private void cancleticketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleticketBtnActionPerformed
        // TODO add your handling code here:
        CancleTicketFram fram=new CancleTicketFram();
        fram.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancleticketBtnActionPerformed

    private void passangerinfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passangerinfoBtnActionPerformed
        // TODO add your handling code here:
        PassengerInfoFram fram=new PassengerInfoFram();
        fram.setVisible(true);
        dispose();
    }//GEN-LAST:event_passangerinfoBtnActionPerformed

    private void driverinfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverinfoBtnActionPerformed
        // TODO add your handling code here:
        DriverInfoFram fram=new DriverInfoFram();
        fram.setVisible(true);
        dispose();
    }//GEN-LAST:event_driverinfoBtnActionPerformed

    private void myprofilelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myprofilelbtnActionPerformed
        // TODO add your handling code here:
        MyProfileFram fram=new MyProfileFram();
        fram.setVisible(true);
        dispose();
    }//GEN-LAST:event_myprofilelbtnActionPerformed

    private void paidmonyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidmonyBtnActionPerformed
        // TODO add your handling code here:
        PassengerListFram fram=new PassengerListFram();
        fram.setVisible(true);
        dispose();
    }//GEN-LAST:event_paidmonyBtnActionPerformed

    private void notificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBtnActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Your ticket booked Successfully");
    }//GEN-LAST:event_notificationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyticketBtn;
    private javax.swing.JButton cancleticketBtn;
    private javax.swing.JButton driverinfoBtn;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton myprofilelbtn;
    private javax.swing.JButton notificationBtn;
    private javax.swing.JButton paidmonyBtn;
    private javax.swing.JButton passangerinfoBtn;
    private javax.swing.JButton supervisorinfoBtn;
    private javax.swing.JButton ticketinfoBtn;
    // End of variables declaration//GEN-END:variables
}
